name: Deploy React to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - name: Checkout code
        uses: actions/checkout@v3

      # Node setup
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      # Install deps
      - name: Install dependencies
        run: npm install

      # Build
      - name: Build project
        run: npm run build

      # Debug (VERY IMPORTANT)
      - name: Verify build files
        run: ls -la web/dist

      # Clean old files on server
      - name: Clean server folder
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            rm -rf /home/ubuntu/projects/web/*

      # Upload FULL build folder
      - name: Deploy to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "web/dist/"
          target: "/home/ubuntu/projects/web"
          strip_components: 2
